# Source: ResNet18 GTSRB mapping
SIGN_NAMES = [
    "Speed limit 20",
    "Speed limit 30",
    "Speed limit 50",
    "Speed limit 60",
    "Speed limit 70",
    "Speed limit 80",
    "End of speed limit 80",
    "Speed limit 100",
    "Speed limit 120",
    "No passing",
    "No passing for vehicles over 3.5 tons",
    "Right-of-way at next intersection",
    "Priority road",
    "Yield",
    "Stop",
    "No vehicles",
    "No trucks",
    "No entry",
    "Danger",
    "Bend left",
    "Bend right",
    "Double bend",
    "Rough road",
    "Slippery road",
    "Road narrows on the right",
    "Road works",
    "Traffic signals",
    "Pedestrians",
    "Children crossing",
    "Bicycles crossing",
    "Snow/ice",
    "Wild animals",
    "End of all speed and passing limits",
    "Turn right",
    "Turn left",
    "Go straight",
    "Go straight or right",
    "Go straight or left",
    "Keep right",
    "Keep left",
    "Roundabout mandatory",
    "End of no passing",
    "End of no passing by vehicles over 3.5 tons"
]
